// Package main implements dependgen, a code generator for testify/depend test suites.
//
// dependgen automates the creation of dependency configuration for testify test suites
// by scanning test files for @dependsOn comments and generating the required registry,
// execution order, and dependency graph.
//
// # Installation
//
// For Go 1.24+ (recommended):
//
//	go get -tool github.com/srgg/testify/depend/cmd/dependgen@latest
//
// For Go < 1.24:
//
//	go install github.com/srgg/testify/depend/cmd/dependgen@latest
//
// # Usage
//
// Add a go:generate directive to your test file:
//
//	//go:generate go run github.com/srgg/testify/depend/cmd/dependgen
//
// Or with Go 1.24+ tool directive:
//
//	//go:generate go tool github.com/srgg/testify/depend/cmd/dependgen
//
// Then run:
//
//	go generate ./...
//
// # Operation Modes
//
// 1. Auto-detect mode (recommended):
//   - Triggered when run via go:generate (GOFILE environment variable set)
//   - Scans only the file containing the go:generate directive
//   - Verifies the file uses depend.RunSuite
//   - Requires exactly one test suite in the file
//   - Generates <testfile>_depend_test.go (e.g., simple_test.go → simple_depend_test.go)
//
// 2. Explicit suite mode:
//   - Usage: dependgen SuiteName
//   - Scans all *_test.go files in the current directory
//   - Generates code only for the specified suite
//   - Useful for multi-suite packages
//
// 3. Multi-suite mode:
//   - Usage: dependgen (without GOFILE set)
//   - Scans all *_test.go files in the current directory
//   - Generates code for all suites that use depend.RunSuite
//   - Generates one file per source file (multiple suites in same file → one generated file)
//
// # Generated Code
//
// For each suite, dependgen creates a file containing:
//   - TestRegistry: Map of test names to test method functions
//   - TestOrder: Slice defining the execution order (declaration order)
//   - Dependencies: Dependency graph parsed from @dependsOn comments
//   - GeneratedDependConfig(): Method that returns the configuration
//
// Example generated code for SimpleSuite:
//
//	// Code generated by dependgen — DO NOT EDIT.
//	package examples
//
//	import "github.com/srgg/testify/depend"
//
//	var SimpleSuiteTestRegistry = map[string]func(any){
//	    "TestA": func(s any) { s.(*SimpleSuite).TestA() },
//	    "TestB": func(s any) { s.(*SimpleSuite).TestB() },
//	}
//
//	var SimpleSuiteTestOrder = []string{"TestA", "TestB"}
//
//	var SimpleSuiteDependencies = depend.Depends(func(s any) *depend.Dep {
//	    dep := new(depend.Dep)
//	    dep.On("TestB", "TestA")
//	    return dep
//	})
//
//	func (s *SimpleSuite) GeneratedDependConfig() *depend.SuiteConfig {
//	    return &depend.SuiteConfig{
//	        Registry: SimpleSuiteTestRegistry,
//	        Order:    SimpleSuiteTestOrder,
//	        Deps:     SimpleSuiteDependencies,
//	    }
//	}
//
// # Suite Detection
//
// dependgen identifies test suites by finding struct types that:
//   - Embed suite.Suite (from github.com/stretchr/testify/suite)
//   - Are used with depend.RunSuite in the same file or package
//
// # Test Method Detection
//
// Test methods must:
//   - Be methods on a suite type (pointer receiver)
//   - Have names starting with "Test"
//   - Take no parameters
//
// # Dependency Comments
//
// Use @dependsOn comments to declare dependencies:
//
//	// @dependsOn TestSetup
//	func (s *Suite) TestProcess() { ... }
//
//	// @dependsOn TestA, TestB
//	func (s *Suite) TestC() { ... }
//
// Multiple dependencies can be comma-separated or specified in multiple comments.
//
// # Error Handling
//
// dependgen will fail with clear error messages when:
//   - File doesn't use depend.RunSuite (auto-detect mode)
//   - Multiple suites found in a single file (auto-detect mode)
//   - No test suite found
//   - Specified suite not found (explicit mode)
//   - No test methods found in suite
//
// # CI/CD Integration
//
// Verify generated code is up-to-date:
//
//	go generate ./...
//	git diff --exit-code  # Fail if generated code is stale
//
// This ensures dependency declarations stay in sync with generated code.
package main
