package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"runtime/debug"
	"strings"
	"text/template"
)

// getVersion returns the module version from build info, or "(devel)" if unavailable.
// This matches the behavior of standard Go tools like stringer.
func getVersion() string {
	info, ok := debug.ReadBuildInfo()
	if !ok {
		return "(devel)"
	}
	if info.Main.Version != "" && info.Main.Version != "(devel)" {
		return info.Main.Version
	}
	return "(devel)"
}

// formatSuiteDocs generates human-readable documentation for a single suite.
func formatSuiteDocs(suite SuiteInfo) string {
	var buf strings.Builder

	fmt.Fprintf(&buf, "// • %s (%s)\n", suite.Name, suite.SourceFile)

	// Check if any tests have dependencies
	hasDependencies := false
	for _, test := range suite.Tests {
		if len(test.DependsOn) > 0 {
			hasDependencies = true
			break
		}
	}

	if !hasDependencies {
		buf.WriteString("//   Dependencies: none\n")
	} else {
		buf.WriteString("//   Dependencies:\n")
		// Only list tests that have dependencies
		for _, test := range suite.Tests {
			if len(test.DependsOn) > 0 {
				deps := strings.Join(test.DependsOn, ", ")
				line := fmt.Sprintf("//     %s: %s", test.Name, deps)
				buf.WriteString(wrapLine(line, 80, "//                            "))
				buf.WriteString("\n")
			}
		}
	}

	// Calculate and display execution order
	order := calculateExecutionOrder(suite)
	orderLine := "//   Order: " + order
	buf.WriteString(wrapLine(orderLine, 80, "//          "))
	buf.WriteString("\n")

	return buf.String()
}

// wrapLine wraps a line at maxLen characters, using the continuation prefix for subsequent lines.
func wrapLine(line string, maxLen int, continuationPrefix string) string {
	if len(line) <= maxLen {
		return line
	}

	var result strings.Builder
	remaining := line

	for len(remaining) > maxLen {
		breakPoint := maxLen

		// Find a good break point (space, comma, or arrow)
		foundBreak := false
		for i := breakPoint; i > 0 && i < len(remaining); i-- {
			if remaining[i] == ' ' || remaining[i] == ',' {
				breakPoint = i
				if remaining[i] == ',' {
					breakPoint++ // Include the comma on this line
				}
				foundBreak = true
				break
			}
		}

		if !foundBreak {
			// No good break point found, break at maxLen
			breakPoint = maxLen
		}

		result.WriteString(remaining[:breakPoint])
		result.WriteString("\n")
		remaining = strings.TrimSpace(remaining[breakPoint:])

		if len(remaining) > 0 {
			result.WriteString(continuationPrefix)
		}
	}

	if len(remaining) > 0 {
		result.WriteString(remaining)
	}

	return result.String()
}

// calculateExecutionOrder determines the test execution order based on dependencies.
// Returns a string representation using arrows (→) to show the sequence.
func calculateExecutionOrder(suite SuiteInfo) string {
	if len(suite.Tests) == 0 {
		return ""
	}

	// Build dependency map
	deps := make(map[string][]string)
	for _, test := range suite.Tests {
		deps[test.Name] = test.DependsOn
	}

	// Topological sort to get execution order
	var order []string
	visited := make(map[string]struct{})

	var visit func(string)
	visit = func(testName string) {
		if _, exists := visited[testName]; exists {
			return
		}
		visited[testName] = struct{}{}

		// Visit dependencies first
		for _, dep := range deps[testName] {
			visit(dep)
		}

		order = append(order, testName)
	}

	// Visit all tests
	for _, test := range suite.Tests {
		visit(test.Name)
	}

	return strings.Join(order, " → ")
}

// Generator handles code generation for test suites.
// It encapsulates the template and configuration needed to generate
// dependency configuration code for testify/depend test suites.
type Generator struct {
	tpl *template.Template
	cfg *Config
}

// NewGenerator creates a new code generator with the given configuration.
// The template is parsed at creation time and is safe for concurrent use.
func NewGenerator(cfg *Config) *Generator {
	// Register template helper functions
	funcMap := template.FuncMap{
		"version":   getVersion,
		"suiteDocs": formatSuiteDocs,
	}

	tpl := template.Must(template.New("reg").Funcs(funcMap).Parse(`{{- range .BuildTags}}
{{.}}
{{end -}}
// Code generated by testify/dependgen {{version}}. DO NOT EDIT.
//
{{range $i, $suite := .Suites -}}
{{if $i}}//
{{end}}{{suiteDocs $suite}}{{end}}
package {{.Package}}

import "github.com/srgg/testify/depend"
{{range .Suites}}
{{- $suite := . }}
var {{.Name}}TestRegistry = map[string]func(any){
{{- range .Tests }}
	"{{.Name}}": func(s any) { s.(*{{$suite.Name}}).{{.Name}}() },
{{- end }}
}

var {{.Name}}TestOrder = []string{
{{- range .Tests }}
	"{{.Name}}",
{{- end }}
}

var {{.Name}}Dependencies = depend.Depends(func(s any) *depend.Dep {
	dep := new(depend.Dep)
{{- range .Tests }}
{{- if .DependsOn }}
	dep.On("{{.Name}}"{{range .DependsOn}}, "{{.}}"{{end}})
{{- end }}
{{- end }}
	return dep
})

// GeneratedDependConfig returns the dependency configuration for {{.Name}}.
// This method allows {{.Name}} to be used with depend.RunSuite(t, suite).
// DO NOT implement this method manually - it is auto-generated.
func (s *{{.Name}}) GeneratedDependConfig() *depend.SuiteConfig {
	return &depend.SuiteConfig{
		Registry: {{.Name}}TestRegistry,
		Order:    {{.Name}}TestOrder,
		Deps:     {{.Name}}Dependencies,
	}
}
{{end}}`))

	return &Generator{
		tpl: tpl,
		cfg: cfg,
	}
}

// Generate generates code files for all specified suites.
// Groups suites by source file and generates one file per source file.
// Returns an error if file generation fails.
func (g *Generator) Generate(suitesToGenerate []SuiteInfo) error {
	verbosef(g.cfg, fmt.Sprintf("Generating code for %d suite(s)...", len(suitesToGenerate)))

	// Group suites by source file
	suitesByFile := make(map[string][]SuiteInfo)
	for _, suite := range suitesToGenerate {
		// Skip suites with no tests (handle empty suites)
		skip, err := g.handleEmptyTestSuite(suite)
		if err != nil {
			return err
		}
		if skip {
			continue
		}

		suitesByFile[suite.SourceFile] = append(suitesByFile[suite.SourceFile], suite)
	}

	if len(suitesByFile) == 0 {
		return fmt.Errorf("no files generated - no test methods found in any suite")
	}

	// Generate one file per source file
	for sourceFile, suites := range suitesByFile {
		if err := g.generateFile(sourceFile, suites); err != nil {
			return fmt.Errorf("failed to generate code for %s: %w", sourceFile, err)
		}
	}

	return nil
}

// generateFile generates the code file for suites from a single source file.
// All suites from the same source file are written to one generated file.
// Uses atomic write pattern to prevent partial file corruption if interrupted.
func (g *Generator) generateFile(sourceFile string, suites []SuiteInfo) error {
	if len(suites) == 0 {
		return nil
	}

	// All suites from the same file have the same package and build tags
	packageName := suites[0].Package
	buildTags := suites[0].BuildTags

	var buf bytes.Buffer
	if err := g.tpl.Execute(&buf, map[string]any{
		"Package":   packageName,
		"BuildTags": buildTags,
		"Suites":    suites,
	}); err != nil {
		return err
	}

	// Generate filename based on a source file: runtime_test.go → runtime_depend_test.go
	// This creates a clear 1:1 mapping between source and generated files
	baseName := strings.TrimSuffix(sourceFile, "_test.go")
	filename := baseName + "_depend_test.go"
	output := filepath.Join(g.cfg.WorkingDir, filename)

	// Count total tests across all suites
	totalTests := 0
	for _, suite := range suites {
		totalTests += len(suite.Tests)
	}

	// Use atomic write to prevent partial file corruption
	if err := atomicWriteFile(output, buf.Bytes(), 0666); err != nil {
		return fmt.Errorf("failed to write %s: %w", output, err)
	}

	verbosef(g.cfg, fmt.Sprintf("Generated: %s (%d suite(s), %d tests)", output, len(suites), totalTests))
	return nil
}

// handleEmptyTestSuite handles the case where a suite has no test methods.
// Returns true if the suite should be skipped, or an error if it's a fatal condition.
func (g *Generator) handleEmptyTestSuite(suite SuiteInfo) (bool, error) {
	if len(suite.Tests) > 0 {
		return false, nil
	}

	if g.cfg.AutoDetectMode || g.cfg.TargetSuite != "" {
		return false, fmt.Errorf("no test methods found for suite %s", suite.Name)
	}

	verbosef(g.cfg, fmt.Sprintf("Warning: No test methods found for suite %s, skipping", suite.Name))
	return true, nil
}

// atomicWriteFile writes data to a file atomically by writing to a temporary file
// and then renaming it. This prevents partial file corruption if the process is
// interrupted during writing.
//
// On POSIX systems (Linux, macOS), os.Rename() is atomic when the source and destination
// are in the same directory. On Windows, if the destination file exists, we remove it
// first, which creates a small race window but is the best we can do with Go's standard
// library without platform-specific code.
func atomicWriteFile(path string, data []byte, perm os.FileMode) error {
	dir := filepath.Dir(path)

	// Create temporary file in the same directory (required for atomic rename on POSIX)
	tmpFile, err := os.CreateTemp(dir, ".dependgen-*.tmp")
	if err != nil {
		return fmt.Errorf("failed to create temp file: %w", err)
	}
	tmpPath := tmpFile.Name()

	// Ensure cleanup on error
	succeeded := false
	defer func() {
		if !succeeded {
			tmpFile.Close()
			os.Remove(tmpPath)
		}
	}()

	// Write data to temporary file
	if _, err := tmpFile.Write(data); err != nil {
		return fmt.Errorf("failed to write to temp file: %w", err)
	}

	// Close the file before renaming (required on Windows)
	if err := tmpFile.Close(); err != nil {
		return fmt.Errorf("failed to close temp file: %w", err)
	}

	// Set permissions on the temporary file
	if err := os.Chmod(tmpPath, perm); err != nil {
		return fmt.Errorf("failed to set permissions: %w", err)
	}

	// On Windows, os.Rename fails if the destination exists, so remove it first.
	// This creates a small race window on Windows, but it is unavoidable without
	// platform-specific code. On POSIX systems, Rename atomically replaces.
	if _, err := os.Stat(path); err == nil {
		// File exists - on Windows, we need to remove it first
		if err := os.Remove(path); err != nil {
			return fmt.Errorf("failed to remove existing file: %w", err)
		}
	}

	// Rename a temp file to the final destination (atomic on POSIX)
	if err := os.Rename(tmpPath, path); err != nil {
		return fmt.Errorf("failed to rename temp file: %w", err)
	}

	succeeded = true
	return nil
}
