package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/suite"
)

type GeneratorSuite struct {
	suite.Suite
}

func (s *GeneratorSuite) TestGeneratedFilename() {
	// GOAL: Verify generated filenames follow source file naming convention
	//
	// TEST SCENARIO: Source test files → Generate filename → Check 1:1 mapping

	testCases := []struct {
		name             string
		sourceFile       string
		expectedFilename string
	}{
		{
			name:             "Simple test file",
			sourceFile:       "my_test.go",
			expectedFilename: "my_depend_test.go",
		},
		{
			name:             "Multi-word test file",
			sourceFile:       "simple_suite_test.go",
			expectedFilename: "simple_suite_depend_test.go",
		},
		{
			name:             "Runtime test file",
			sourceFile:       "runtime_test.go",
			expectedFilename: "runtime_depend_test.go",
		},
		{
			name:             "HTTP handler test file",
			sourceFile:       "http_handler_test.go",
			expectedFilename: "http_handler_depend_test.go",
		},
		{
			name:             "API test file",
			sourceFile:       "api_test.go",
			expectedFilename: "api_depend_test.go",
		},
		{
			name:             "Complex name test file",
			sourceFile:       "https_client_test.go",
			expectedFilename: "https_client_depend_test.go",
		},
	}

	for _, tc := range testCases {
		s.Run(tc.name, func() {
			baseName := strings.TrimSuffix(tc.sourceFile, "_test.go")
			actualFilename := baseName + "_depend_test.go"

			s.Assert().Equal(tc.expectedFilename, actualFilename,
				"MUST generate filename with 1:1 mapping from source file")
		})
	}
}

func (s *GeneratorSuite) TestGenerateFile() {
	// GOAL: Verify generateFile creates valid Go code with all required components
	//
	// TEST SCENARIO: Generate file for suite(s) → Parse output → Verify code structure

	type testCase struct {
		name             string
		sourceFile       string
		suites           []SuiteInfo
		expectedFilename string
		expectedContent  string
	}

	testCases := []testCase{
		{
			name:       "Generates valid Go code with all components",
			sourceFile: "my_test.go",
			suites: []SuiteInfo{
				{
					Name:    "MySuite",
					Package: "testpkg",
					Tests: []TestMethodInfo{
						{Name: "TestA", DependsOn: nil},
						{Name: "TestB", DependsOn: []string{"TestA"}},
						{Name: "TestC", DependsOn: []string{"TestA", "TestB"}},
					},
					SourceFile: "my_test.go",
				},
			},
			expectedFilename: "my_depend_test.go",
			expectedContent: `// Code generated by testify/dependgen (devel). DO NOT EDIT.
//
// • MySuite (my_test.go)
//   Dependencies:
//     TestB: TestA
//     TestC: TestA, TestB
//   Order: TestA → TestB → TestC

package testpkg

import "github.com/srgg/testify/depend"

var MySuiteTestRegistry = map[string]func(any){
	"TestA": func(s any) { s.(*MySuite).TestA() },
	"TestB": func(s any) { s.(*MySuite).TestB() },
	"TestC": func(s any) { s.(*MySuite).TestC() },
}

var MySuiteTestOrder = []string{
	"TestA",
	"TestB",
	"TestC",
}

var MySuiteDependencies = depend.Depends(func(s any) *depend.Dep {
	dep := new(depend.Dep)
	dep.On("TestB", "TestA")
	dep.On("TestC", "TestA", "TestB")
	return dep
})

// GeneratedDependConfig returns the dependency configuration for MySuite.
// This method allows MySuite to be used with depend.RunSuite(t, suite).
// DO NOT implement this method manually - it is auto-generated.
func (s *MySuite) GeneratedDependConfig() *depend.SuiteConfig {
	return &depend.SuiteConfig{
		Registry: MySuiteTestRegistry,
		Order:    MySuiteTestOrder,
		Deps:     MySuiteDependencies,
	}
}
`,
		},
		{
			name:       "Handles suite with no dependencies",
			sourceFile: "simple_test.go",
			suites: []SuiteInfo{
				{
					Name:    "SimpleSuite",
					Package: "testpkg",
					Tests: []TestMethodInfo{
						{Name: "TestA", DependsOn: nil},
						{Name: "TestB", DependsOn: nil},
					},
					SourceFile: "simple_test.go",
				},
			},
			expectedFilename: "simple_depend_test.go",
			expectedContent: `// Code generated by testify/dependgen (devel). DO NOT EDIT.
//
// • SimpleSuite (simple_test.go)
//   Dependencies: none
//   Order: TestA → TestB

package testpkg

import "github.com/srgg/testify/depend"

var SimpleSuiteTestRegistry = map[string]func(any){
	"TestA": func(s any) { s.(*SimpleSuite).TestA() },
	"TestB": func(s any) { s.(*SimpleSuite).TestB() },
}

var SimpleSuiteTestOrder = []string{
	"TestA",
	"TestB",
}

var SimpleSuiteDependencies = depend.Depends(func(s any) *depend.Dep {
	dep := new(depend.Dep)
	return dep
})

// GeneratedDependConfig returns the dependency configuration for SimpleSuite.
// This method allows SimpleSuite to be used with depend.RunSuite(t, suite).
// DO NOT implement this method manually - it is auto-generated.
func (s *SimpleSuite) GeneratedDependConfig() *depend.SuiteConfig {
	return &depend.SuiteConfig{
		Registry: SimpleSuiteTestRegistry,
		Order:    SimpleSuiteTestOrder,
		Deps:     SimpleSuiteDependencies,
	}
}
`,
		},
		{
			name:       "Generates correct file for multi-word source file",
			sourceFile: "http_handler_test.go",
			suites: []SuiteInfo{
				{
					Name:    "HTTPHandlerSuite",
					Package: "testpkg",
					Tests: []TestMethodInfo{
						{Name: "TestSetup", DependsOn: nil},
					},
					SourceFile: "http_handler_test.go",
				},
			},
			expectedFilename: "http_handler_depend_test.go",
			expectedContent: `// Code generated by testify/dependgen (devel). DO NOT EDIT.
//
// • HTTPHandlerSuite (http_handler_test.go)
//   Dependencies: none
//   Order: TestSetup

package testpkg

import "github.com/srgg/testify/depend"

var HTTPHandlerSuiteTestRegistry = map[string]func(any){
	"TestSetup": func(s any) { s.(*HTTPHandlerSuite).TestSetup() },
}

var HTTPHandlerSuiteTestOrder = []string{
	"TestSetup",
}

var HTTPHandlerSuiteDependencies = depend.Depends(func(s any) *depend.Dep {
	dep := new(depend.Dep)
	return dep
})

// GeneratedDependConfig returns the dependency configuration for HTTPHandlerSuite.
// This method allows HTTPHandlerSuite to be used with depend.RunSuite(t, suite).
// DO NOT implement this method manually - it is auto-generated.
func (s *HTTPHandlerSuite) GeneratedDependConfig() *depend.SuiteConfig {
	return &depend.SuiteConfig{
		Registry: HTTPHandlerSuiteTestRegistry,
		Order:    HTTPHandlerSuiteTestOrder,
		Deps:     HTTPHandlerSuiteDependencies,
	}
}
`,
		},
		{
			name:       "Generates file with multiple suites from same source",
			sourceFile: "multi_test.go",
			suites: []SuiteInfo{
				{
					Name:    "FirstSuite",
					Package: "testpkg",
					Tests: []TestMethodInfo{
						{Name: "TestA", DependsOn: nil},
					},
					SourceFile: "multi_test.go",
				},
				{
					Name:    "SecondSuite",
					Package: "testpkg",
					Tests: []TestMethodInfo{
						{Name: "TestX", DependsOn: nil},
					},
					SourceFile: "multi_test.go",
				},
			},
			expectedFilename: "multi_depend_test.go",
			expectedContent: `// Code generated by testify/dependgen (devel). DO NOT EDIT.
//
// • FirstSuite (multi_test.go)
//   Dependencies: none
//   Order: TestA
//
// • SecondSuite (multi_test.go)
//   Dependencies: none
//   Order: TestX

package testpkg

import "github.com/srgg/testify/depend"

var FirstSuiteTestRegistry = map[string]func(any){
	"TestA": func(s any) { s.(*FirstSuite).TestA() },
}

var FirstSuiteTestOrder = []string{
	"TestA",
}

var FirstSuiteDependencies = depend.Depends(func(s any) *depend.Dep {
	dep := new(depend.Dep)
	return dep
})

// GeneratedDependConfig returns the dependency configuration for FirstSuite.
// This method allows FirstSuite to be used with depend.RunSuite(t, suite).
// DO NOT implement this method manually - it is auto-generated.
func (s *FirstSuite) GeneratedDependConfig() *depend.SuiteConfig {
	return &depend.SuiteConfig{
		Registry: FirstSuiteTestRegistry,
		Order:    FirstSuiteTestOrder,
		Deps:     FirstSuiteDependencies,
	}
}

var SecondSuiteTestRegistry = map[string]func(any){
	"TestX": func(s any) { s.(*SecondSuite).TestX() },
}

var SecondSuiteTestOrder = []string{
	"TestX",
}

var SecondSuiteDependencies = depend.Depends(func(s any) *depend.Dep {
	dep := new(depend.Dep)
	return dep
})

// GeneratedDependConfig returns the dependency configuration for SecondSuite.
// This method allows SecondSuite to be used with depend.RunSuite(t, suite).
// DO NOT implement this method manually - it is auto-generated.
func (s *SecondSuite) GeneratedDependConfig() *depend.SuiteConfig {
	return &depend.SuiteConfig{
		Registry: SecondSuiteTestRegistry,
		Order:    SecondSuiteTestOrder,
		Deps:     SecondSuiteDependencies,
	}
}
`,
		},
	}

	for _, tc := range testCases {
		s.Run(tc.name, func() {
			tmpDir := NewTempDirFixture(s.T()).Build()
			cfg := &Config{WorkingDir: tmpDir}
			gen := NewGenerator(cfg)

			err := gen.generateFile(tc.sourceFile, tc.suites)
			s.Require().NoError(err, "MUST generate file without error")

			expectedPath := filepath.Join(tmpDir, tc.expectedFilename)
			content, err := os.ReadFile(expectedPath)
			s.Require().NoError(err, "MUST read generated file")

			s.Assert().Equal(tc.expectedContent, string(content), "MUST match expected file content exactly")
		})
	}
}

func (s *GeneratorSuite) TestGenerate() {
	// GOAL: Verify Generate() correctly orchestrates file generation for multiple suites
	//
	// TEST SCENARIO: Various suite configurations → Generate() called → Correct files created or error returned

	type testCase struct {
		name              string
		suitesToGenerate  []SuiteInfo
		cfg               *Config
		expectError       bool
		errorContains     string
		expectedFileCount int
		expectedFileNames []string
	}

	testCases := []testCase{
		{
			name: "Generates multiple suite files successfully",
			suitesToGenerate: []SuiteInfo{
				{
					Name:    "FirstSuite",
					Package: "testpkg",
					Tests: []TestMethodInfo{
						{Name: "TestA", DependsOn: nil},
						{Name: "TestB", DependsOn: []string{"TestA"}},
					},
					SourceFile: "first_test.go",
				},
				{
					Name:    "SecondSuite",
					Package: "testpkg",
					Tests: []TestMethodInfo{
						{Name: "TestX", DependsOn: nil},
					},
					SourceFile: "second_test.go",
				},
			},
			cfg:               &Config{WorkingDir: ""},
			expectError:       false,
			expectedFileCount: 2,
			expectedFileNames: []string{"first_depend_test.go", "second_depend_test.go"},
		},
		{
			name: "Empty suite in auto-detect mode returns error",
			suitesToGenerate: []SuiteInfo{
				{
					Name:    "EmptySuite",
					Package: "testpkg",
					Tests:   []TestMethodInfo{},
				},
			},
			cfg:           &Config{WorkingDir: "", AutoDetectMode: true},
			expectError:   true,
			errorContains: "no test methods found for suite EmptySuite",
		},
		{
			name: "Empty suite in explicit mode returns error",
			suitesToGenerate: []SuiteInfo{
				{
					Name:    "EmptySuite",
					Package: "testpkg",
					Tests:   []TestMethodInfo{},
				},
			},
			cfg:           &Config{WorkingDir: "", TargetSuite: "EmptySuite"},
			expectError:   true,
			errorContains: "no test methods found for suite EmptySuite",
		},
		{
			name: "Empty suite in multi-suite mode skips with warning",
			suitesToGenerate: []SuiteInfo{
				{
					Name:       "EmptySuite",
					Package:    "testpkg",
					Tests:      []TestMethodInfo{},
					SourceFile: "empty_test.go",
				},
				{
					Name:    "ValidSuite",
					Package: "testpkg",
					Tests: []TestMethodInfo{
						{Name: "TestA", DependsOn: nil},
					},
					SourceFile: "valid_test.go",
				},
			},
			cfg:               &Config{WorkingDir: "", AutoDetectMode: false, TargetSuite: ""},
			expectError:       false,
			expectedFileCount: 1,
			expectedFileNames: []string{"valid_depend_test.go"},
		},
		{
			name: "All suites empty returns error",
			suitesToGenerate: []SuiteInfo{
				{
					Name:    "EmptySuite1",
					Package: "testpkg",
					Tests:   []TestMethodInfo{},
				},
				{
					Name:    "EmptySuite2",
					Package: "testpkg",
					Tests:   []TestMethodInfo{},
				},
			},
			cfg:           &Config{WorkingDir: "", AutoDetectMode: false, TargetSuite: ""},
			expectError:   true,
			errorContains: "no files generated - no test methods found in any suite",
		},
		{
			name: "Single suite generates successfully",
			suitesToGenerate: []SuiteInfo{
				{
					Name:    "MySuite",
					Package: "testpkg",
					Tests: []TestMethodInfo{
						{Name: "TestA", DependsOn: nil},
					},
					SourceFile: "my_test.go",
				},
			},
			cfg:               &Config{WorkingDir: ""},
			expectError:       false,
			expectedFileCount: 1,
			expectedFileNames: []string{"my_depend_test.go"},
		},
	}

	for _, tc := range testCases {
		s.Run(tc.name, func() {
			tmpDir := NewTempDirFixture(s.T()).Build()
			tc.cfg.WorkingDir = tmpDir
			gen := NewGenerator(tc.cfg)

			err := gen.Generate(tc.suitesToGenerate)

			if tc.expectError {
				// All assertions MUST execute
				s.Assert().Error(err, "Expected error for: %s", tc.name)
				s.Assert().Contains(err.Error(), tc.errorContains, "Error message mismatch")
			} else {
				// All assertions MUST execute
				s.Assert().NoError(err, "Expected success for: %s", tc.name)

				// Verify expected files were created
				for _, filename := range tc.expectedFileNames {
					filePath := filepath.Join(tmpDir, filename)
					_, err := os.Stat(filePath)
					s.Assert().NoError(err, "Expected file not created: %s", filename)
				}

				// Count generated files
				files, _ := filepath.Glob(filepath.Join(tmpDir, "*_depend_test.go"))
				s.Assert().Len(files, tc.expectedFileCount, "Generated file count mismatch")
			}
		})
	}
}

func (s *GeneratorSuite) TestHandleEmptyTestSuite() {
	// GOAL: Verify handleEmptyTestSuite correctly handles empty suites based on mode
	//
	// TEST SCENARIO: Various configs + empty/non-empty tests → handleEmptyTestSuite called → Correct skip/error decision

	type testCase struct {
		name        string
		cfg         *Config
		suiteName   string
		tests       []TestMethodInfo
		expectSkip  bool
		expectError bool
	}

	testCases := []testCase{
		{
			name:        "Non-empty suite returns false false",
			cfg:         &Config{},
			suiteName:   "MySuite",
			tests:       []TestMethodInfo{{Name: "TestA", DependsOn: nil}},
			expectSkip:  false,
			expectError: false,
		},
		{
			name:        "Empty suite in auto-detect mode returns false true (error)",
			cfg:         &Config{AutoDetectMode: true},
			suiteName:   "MySuite",
			tests:       []TestMethodInfo{},
			expectSkip:  false,
			expectError: true,
		},
		{
			name:        "Empty suite in explicit mode returns false true (error)",
			cfg:         &Config{TargetSuite: "MySuite"},
			suiteName:   "MySuite",
			tests:       []TestMethodInfo{},
			expectSkip:  false,
			expectError: true,
		},
		{
			name:        "Empty suite in multi-suite mode returns true false (skip)",
			cfg:         &Config{AutoDetectMode: false, TargetSuite: ""},
			suiteName:   "MySuite",
			tests:       []TestMethodInfo{},
			expectSkip:  true,
			expectError: false,
		},
	}

	for _, tc := range testCases {
		s.Run(tc.name, func() {
			gen := NewGenerator(tc.cfg)
			suiteInfo := SuiteInfo{
				Name:  tc.suiteName,
				Tests: tc.tests,
			}
			skip, err := gen.handleEmptyTestSuite(suiteInfo)

			// All assertions MUST execute
			s.Assert().Equal(tc.expectSkip, skip, "Skip value mismatch")
			if tc.expectError {
				s.Assert().Error(err, "Expected error for: %s", tc.name)
			} else {
				s.Assert().NoError(err, "Expected no error for: %s", tc.name)
			}
		})
	}
}

func (s *GeneratorSuite) TestAtomicWriteFile() {
	// GOAL: Verify atomicWriteFile writes files atomically and cleans up properly
	//
	// TEST SCENARIO: Various write scenarios → atomicWriteFile called → Files written correctly

	type testCase struct {
		name          string
		setupFile     bool   // Create existing file first?
		existingData  string // Data in existing file
		writeData     string // Data to write
		perm          os.FileMode
		badPath       bool // Use invalid path?
		expectError   bool
		errorContains string
	}

	testCases := []testCase{
		{
			name:        "Writes new file successfully",
			setupFile:   false,
			writeData:   "new file content",
			perm:        0644,
			expectError: false,
		},
		{
			name:         "Overwrites existing file successfully",
			setupFile:    true,
			existingData: "old content",
			writeData:    "new content",
			perm:         0644,
			expectError:  false,
		},
		{
			name:        "Sets correct file permissions",
			setupFile:   false,
			writeData:   "test",
			perm:        0600,
			expectError: false,
		},
		{
			name:          "Fails on non-existent directory",
			setupFile:     false,
			writeData:     "test",
			perm:          0644,
			badPath:       true,
			expectError:   true,
			errorContains: "failed to create temp file",
		},
		{
			name:        "Handles empty content",
			setupFile:   false,
			writeData:   "",
			perm:        0644,
			expectError: false,
		},
		{
			name:        "Handles large content",
			setupFile:   false,
			writeData:   string(make([]byte, 100000)), // 100KB
			perm:        0644,
			expectError: false,
		},
	}

	for _, tc := range testCases {
		s.Run(tc.name, func() {
			tmpDir := NewTempDirFixture(s.T()).Build()

			var targetPath string
			if tc.badPath {
				targetPath = filepath.Join(tmpDir, "nonexistent", "file.txt")
			} else {
				targetPath = filepath.Join(tmpDir, "test.txt")
			}

			// Setup existing file if needed
			if tc.setupFile {
				err := os.WriteFile(targetPath, []byte(tc.existingData), 0644)
				s.Require().NoError(err, "Failed to setup test file")
			}

			// Execute atomicWriteFile
			err := atomicWriteFile(targetPath, []byte(tc.writeData), tc.perm)

			if tc.expectError {
				// All assertions MUST execute
				s.Assert().Error(err, "Expected error for: %s", tc.name)
				if tc.errorContains != "" {
					s.Assert().Contains(err.Error(), tc.errorContains, "Error message mismatch")
				}
			} else {
				// All assertions MUST execute
				s.Assert().NoError(err, "Expected success for: %s", tc.name)

				// Verify file was written
				content, readErr := os.ReadFile(targetPath)
				s.Assert().NoError(readErr, "Should read written file")
				s.Assert().Equal(tc.writeData, string(content), "Content should match")

				// Verify permissions
				info, statErr := os.Stat(targetPath)
				s.Assert().NoError(statErr, "File should exist")
				s.Assert().Equal(tc.perm, info.Mode().Perm(), "Permissions should match")

				// Verify no temp files left behind
				entries, _ := os.ReadDir(tmpDir)
				for _, entry := range entries {
					s.Assert().NotContains(entry.Name(), ".dependgen-", "No temp files should remain")
					s.Assert().NotContains(entry.Name(), ".tmp", "No temp files should remain")
				}
			}
		})
	}
}

func TestGeneratorSuite(t *testing.T) {
	suite.Run(t, new(GeneratorSuite))
}
