package main

import (
	"go/parser"
	"go/token"
	"os"
	"os/exec"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/suite"
)

// IntegrationSuite tests the dependgen code generator
type IntegrationSuite struct {
	suite.Suite
	binaryPath string
}

// multipleSuitesFile contains two test suites that depend on each other.RunSuite
const multipleSuitesFile = `package test
import (
	"testing"
	"github.com/srgg/testify/depend"
	"github.com/stretchr/testify/suite"
)

type FirstSuite struct {
	suite.Suite
}

func (s *FirstSuite) TestA() {}

type SecondSuite struct {
	suite.Suite
}

func (s *SecondSuite) TestB() {}

func TestSuites(t *testing.T) {
	depend.RunSuite(t, new(FirstSuite))
	depend.RunSuite(t, new(SecondSuite))
}`

// plainTestFile contains a plain test function without any suite
const plainTestFile = `package test
import "testing"

func TestSomething(t *testing.T) {}`

// emptySuiteFile contains a test suite with no test methods
const emptySuiteFile = `package test
import (
	"testing"
	"github.com/srgg/testify/depend"
	"github.com/stretchr/testify/suite"
)

type MySuite struct {
	suite.Suite
}

func TestMySuite(t *testing.T) {
	depend.RunSuite(t, new(MySuite))
}`

// TempDir creates a new temporary directory fixture using the suite's testing context
func (s *IntegrationSuite) TempDir() *TempDirFixture {
	return NewTempDirFixture(s.T())
}

// SetupSuite builds the dependgen binary once for all tests
func (s *IntegrationSuite) SetupSuite() {
	tmpDir := s.T().TempDir()
	s.binaryPath = filepath.Join(tmpDir, "dependgen")

	cmd := exec.Command("go", "build", "-o", s.binaryPath, ".")
	err := cmd.Run()
	s.Require().NoError(err, "MUST successfully build dependgen binary for testing")
}

// runDependgen executes the dependgen binary with given arguments and environment
func (s *IntegrationSuite) runDependgen(dir string, args []string, env map[string]string) ([]byte, error) {
	cmd := exec.Command(s.binaryPath, args...)
	cmd.Dir = dir
	cmd.Env = os.Environ()
	for k, v := range env {
		cmd.Env = append(cmd.Env, k+"="+v)
	}
	return cmd.CombinedOutput()
}

// testSuiteTemplateStr is the unified template for generating test suite files with optional @dependsOn comments
const testSuiteTemplateStr = `package test
import (
	"testing"
{{- if .UseRunSuite }}
	"github.com/srgg/testify/depend"
{{- end }}
	"github.com/stretchr/testify/suite"
)

type {{.SuiteName}} struct {
	suite.Suite
}
{{range $testName, $deps := .Tests}}
{{- if $deps}}
// @dependsOn {{index $deps 0}}{{range $i, $dep := (slice $deps 1)}}, {{$dep}}{{end}}
{{- end}}
func (s *{{$.SuiteName}}) Test{{$testName}}() {}
{{end}}
func Test{{.SuiteName}}(t *testing.T) {
{{- if .UseRunSuite }}
	depend.RunSuite(t, new({{.SuiteName}}))
{{- else }}
	suite.Run(t, new({{.SuiteName}}))
{{- end }}
}`

// assertGeneratedFile verifies that a generated file exists and contains expected strings
func (s *IntegrationSuite) assertGeneratedFile(dir, filename string, expectedContents ...string) string {
	generatedPath := filepath.Join(dir, filename)
	s.Assert().FileExists(generatedPath, "MUST create %s", filename)

	content, err := os.ReadFile(generatedPath)
	s.Require().NoError(err, "MUST read generated file")

	generatedCode := string(content)
	for _, expected := range expectedContents {
		s.Assert().Contains(generatedCode, expected, "MUST contain: %s", expected)
	}

	return generatedCode
}

// assertGenerationFailed verifies that generation failed with the expected complete error message
func (s *IntegrationSuite) assertGenerationFailed(output []byte, err error, expectedErrorMsg string) {
	s.Assert().Error(err, "MUST fail generation")
	s.Assert().Contains(string(output), expectedErrorMsg, "MUST contain complete error message")
}

func (s *IntegrationSuite) TestAutoDetectSingleSuite() {
	// GOAL: Verify auto-detect mode generates correct code for a single suite in GOFILE
	//
	// TEST SCENARIO: Run with a GOFILE set and one suite → file generated → contains expected registry and tests

	testDir := s.TempDir().
		WithTestFile("suite_test.go", testSuiteTemplateStr, map[string]any{
			"SuiteName": "MySuite",
			"Tests": map[string][]string{
				"A": nil,
				"B": nil,
			},
			"UseRunSuite": true,
		}).
		Build()

	output, err := s.runDependgen(testDir, []string{"-v"}, map[string]string{"GOFILE": "suite_test.go"})
	s.Assert().NoError(err, "MUST generate successfully for single suite")

	s.assertGeneratedFile(testDir, "suite_depend_test.go",
		"Code generated by dependgen",
		"MySuiteTestRegistry",
		"TestA",
		"TestB")
	s.Assert().Contains(string(output), "Generated:", "MUST log successful generation")
}

func (s *IntegrationSuite) TestAutoDetectErrorCases() {
	// GOAL: Verify auto-detect mode fails appropriately for invalid scenarios
	//
	// TEST SCENARIO: Run with various invalid inputs → error returned → helpful message provided

	testCases := []struct {
		name             string
		template         string
		params           map[string]any
		expectedErrorMsg string
	}{
		{
			name:     "Multiple suites in GOFILE",
			template: multipleSuitesFile,
			params:   map[string]any{},
			expectedErrorMsg: `dependgen: multiple test suites found in suite_test.go: [FirstSuite SecondSuite]

Specify which suite to generate:
  //go:generate go run github.com/srgg/testify/depend/cmd/dependgen FirstSuite`,
		},
		{
			name:     "No suite in GOFILE",
			template: plainTestFile,
			params:   map[string]any{},
			expectedErrorMsg: `dependgen: file suite_test.go does not use depend.RunSuite

Remove the //go:generate directive or add depend.RunSuite usage`,
		},
		{
			name:     "Suite without depend.RunSuite",
			template: testSuiteTemplateStr,
			params: map[string]any{
				"SuiteName": "MySuite",
				"Tests": map[string][]string{
					"A": nil,
				},
				"UseRunSuite": false,
			},
			expectedErrorMsg: `dependgen: file suite_test.go does not use depend.RunSuite

Remove the //go:generate directive or add depend.RunSuite usage`,
		},
		{
			name:     "Single non-existent dependency",
			template: testSuiteTemplateStr,
			params: map[string]any{
				"SuiteName": "MySuite",
				"Tests": map[string][]string{
					"A": nil,
					"B": {"TestNonExistent"},
				},
				"UseRunSuite": true,
			},
			expectedErrorMsg: `dependgen: dependency validation failed for suite MySuite:

Invalid dependency in TestB: TestNonExistent does not exist`,
		},
		{
			name:     "Multiple non-existent dependencies",
			template: testSuiteTemplateStr,
			params: map[string]any{
				"SuiteName": "MySuite",
				"Tests": map[string][]string{
					"A": nil,
					"B": {"TestA", "TestNonExistent", "TestAlsoMissing"},
				},
				"UseRunSuite": true,
			},
			expectedErrorMsg: `dependgen: dependency validation failed for suite MySuite:

Invalid dependency in TestB: TestNonExistent does not exist
Invalid dependency in TestB: TestAlsoMissing does not exist`,
		},
		{
			name:     "Self dependency",
			template: testSuiteTemplateStr,
			params: map[string]any{
				"SuiteName": "MySuite",
				"Tests": map[string][]string{
					"A": {"TestA"},
				},
				"UseRunSuite": true,
			},
			expectedErrorMsg: `dependgen: dependency validation failed for suite MySuite:

Invalid dependency in TestA: test cannot depend on itself`,
		},
		{
			name:     "Direct circular dependency",
			template: testSuiteTemplateStr,
			params: map[string]any{
				"SuiteName": "MySuite",
				"Tests": map[string][]string{
					"A": {"TestB"},
					"B": {"TestA"},
				},
				"UseRunSuite": true,
			},
			expectedErrorMsg: `dependgen: dependency validation failed for suite MySuite:

Circular dependency detected: TestA → TestB → TestA`,
		},
		{
			name:     "Transitive circular dependency",
			template: testSuiteTemplateStr,
			params: map[string]any{
				"SuiteName": "MySuite",
				"Tests": map[string][]string{
					"A": {"TestB"},
					"B": {"TestC"},
					"C": {"TestA"},
				},
				"UseRunSuite": true,
			},
			expectedErrorMsg: `dependgen: dependency validation failed for suite MySuite:

Circular dependency detected: TestA → TestB → TestC → TestA`,
		},
		{
			name:             "No test methods in suite",
			template:         emptySuiteFile,
			params:           map[string]any{},
			expectedErrorMsg: `dependgen: no test methods found for suite MySuite`,
		},
	}

	for _, tc := range testCases {
		s.Run(tc.name, func() {
			testDir := s.TempDir().
				WithTestFile("suite_test.go", tc.template, tc.params).
				Build()

			output, err := s.runDependgen(testDir, []string{}, map[string]string{"GOFILE": "suite_test.go"})

			s.assertGenerationFailed(output, err, tc.expectedErrorMsg)
		})
	}
}

func (s *IntegrationSuite) TestExplicitSuiteName() {
	// GOAL: Verify explicit suite name mode generates code for specified suite
	//
	// TEST SCENARIO: Run with suite name argument → file generated → contains only specified suite

	testDir := s.TempDir().
		WithTestFile("suite_test.go", testSuiteTemplateStr, map[string]any{
			"SuiteName": "MySuite",
			"Tests": map[string][]string{
				"A": nil,
			},
			"UseRunSuite": true,
		}).
		Build()

	output, err := s.runDependgen(testDir, []string{"-v", "MySuite"}, map[string]string{})
	s.Assert().NoError(err, "MUST generate successfully with explicit suite name")

	s.assertGeneratedFile(testDir, "suite_depend_test.go", "MySuiteTestRegistry")
	s.Assert().Contains(string(output), "Generated:", "MUST log successful generation")
}

func (s *IntegrationSuite) TestMultiWordSuiteNameGeneratesSourceBasedFilename() {
	// GOAL: Verify generated filenames are based on source file, not suite name
	//
	// TEST SCENARIO: Generate code for various suite names → filenames match source file → clear 1:1 mapping

	testCases := []struct {
		suiteName string
	}{
		{suiteName: "TestifyLifecycleSuite"},
		{suiteName: "HTTPHandlerSuite"},
		{suiteName: "APITestSuite"},
		{suiteName: "MyCustomSuite"},
		{suiteName: "SimpleSuite"},
	}

	for _, tc := range testCases {
		s.Run(tc.suiteName, func() {
			testDir := s.TempDir().
				WithTestFile("suite_test.go", testSuiteTemplateStr, map[string]any{
					"SuiteName": tc.suiteName,
					"Tests": map[string][]string{
						"A": nil,
					},
					"UseRunSuite": true,
				}).
				Build()

			_, err := s.runDependgen(testDir, []string{tc.suiteName}, map[string]string{})
			s.Assert().NoError(err, "MUST generate successfully for %s", tc.suiteName)

			// All suites in suite_test.go generate suite_depend_test.go
			s.assertGeneratedFile(testDir, "suite_depend_test.go",
				tc.suiteName+"TestRegistry",
				tc.suiteName+"TestOrder",
				tc.suiteName+"Dependencies")
		})
	}
}

func (s *IntegrationSuite) TestExplicitModeSkipsFilesWithoutRunSuite() {
	// GOAL: Verify explicit mode only processes files that use depend.RunSuite
	//
	// TEST SCENARIO: Run with explicit suite name and mixed files → only RunSuite file processed → Suite1 ignored

	testDir := s.TempDir().
		WithTestFile("suite1_test.go", testSuiteTemplateStr, map[string]any{
			"SuiteName": "Suite1",
			"Tests": map[string][]string{
				"A": nil,
			},
			"UseRunSuite": false,
		}).
		WithTestFile("suite2_test.go", testSuiteTemplateStr, map[string]any{
			"SuiteName": "Suite2",
			"Tests": map[string][]string{
				"B": nil,
			},
			"UseRunSuite": true,
		}).
		Build()

	_, err := s.runDependgen(testDir, []string{"Suite2"}, map[string]string{})
	s.Assert().NoError(err, "MUST generate successfully for Suite2")

	// Verify Suite2 was generated correctly
	generatedCode := s.assertGeneratedFile(testDir, "suite2_depend_test.go", "Suite2TestRegistry")
	s.Assert().NotContains(generatedCode, "Suite1", "MUST NOT contain Suite1")

	// Verify Suite1 file was NOT generated
	suite1Path := filepath.Join(testDir, "suite1_depend_test.go")
	s.Assert().NoFileExists(suite1Path, "MUST NOT create file for Suite1")
}

func (s *IntegrationSuite) TestParseDependsOnComments() {
	// GOAL: Verify generator correctly parses @dependsOn comments into dependency configuration
	//
	// TEST SCENARIO: Run with various @dependsOn patterns → file generated → contains correct dep.On() calls

	testCases := []struct {
		name             string
		tests            map[string][]string
		expectedDepCalls []string
	}{
		{
			name: "Single dependency chain",
			tests: map[string][]string{
				"A": nil,
				"B": {"TestA"},
				"C": {"TestB"},
			},
			expectedDepCalls: []string{
				`dep.On("TestB", "TestA")`,
				`dep.On("TestC", "TestB")`,
			},
		},
		{
			name: "Multiple dependencies",
			tests: map[string][]string{
				"A": nil,
				"B": nil,
				"C": {"TestA", "TestB"},
			},
			expectedDepCalls: []string{
				`dep.On("TestC", "TestA", "TestB")`,
			},
		},
	}

	for _, tc := range testCases {
		s.Run(tc.name, func() {
			testDir := s.TempDir().WithTestFile("suite_test.go", testSuiteTemplateStr, map[string]any{
				"SuiteName":   "MySuite",
				"Tests":       tc.tests,
				"UseRunSuite": true,
			}).Build()

			_, err := s.runDependgen(testDir, []string{}, map[string]string{"GOFILE": "suite_test.go"})
			s.Assert().NoError(err, "MUST generate successfully with dependencies")

			s.assertGeneratedFile(testDir, "suite_depend_test.go", tc.expectedDepCalls...)
		})
	}
}

func (s *IntegrationSuite) TestMultiSuiteModeScansAllTestFiles() {
	// GOAL: Verify multi-suite mode (no GOFILE, no args) scans all test files and generates for all suites
	//
	// TEST SCENARIO: Run with no arguments and no GOFILE → all test files scanned → file generated for suite using RunSuite

	testDir := s.TempDir().WithTestFile("suite_test.go", testSuiteTemplateStr, map[string]any{
		"SuiteName": "MySuite",
		"Tests": map[string][]string{
			"A": nil,
		},
		"UseRunSuite": true,
	}).Build()

	_, err := s.runDependgen(testDir, []string{}, map[string]string{})
	s.Assert().NoError(err, "MUST generate successfully in multi-suite mode")
	s.assertGeneratedFile(testDir, "suite_depend_test.go", "MySuiteTestRegistry")
}

func (s *IntegrationSuite) TestUsesRunSuiteDetection() {
	// GOAL: Verify usesRunSuite correctly identifies depend.RunSuite usage rejects other patterns
	//
	// TEST SCENARIO: Parse various code patterns → check detection → matches an expected result

	testCases := []struct {
		name     string
		code     string
		expected bool
	}{
		{
			name: "Detects depend.RunSuite",
			code: `package test
import "github.com/srgg/testify/depend"
func TestSuite(t *testing.T) {
	depend.RunSuite(t, new(MySuite))
}`,
			expected: true,
		},
		{
			name: "Does not detect suite.Run",
			code: `package test
import "github.com/stretchr/testify/suite"
func TestSuite(t *testing.T) {
	suite.Run(t, new(MySuite))
}`,
			expected: false,
		},
		{
			name: "Does not detect plain test",
			code: `package test
func TestSomething(t *testing.T) {}`,
			expected: false,
		},
		{
			name: "Does not detect other package RunSuite",
			code: `package test
func TestSuite(t *testing.T) {
	other.RunSuite(t, new(MySuite))
}`,
			expected: false,
		},
	}

	// parseCode is a helper to parse Go code and check usesRunSuite
	parseCode := func(code string) bool {
		fset := token.NewFileSet()
		f, err := parser.ParseFile(fset, "test.go", code, 0)
		s.Require().NoError(err, "MUST parse test code")
		scanner := NewSuiteScanner(&Config{})
		return scanner.usesRunSuite(f)
	}

	for _, tc := range testCases {
		s.Run(tc.name, func() {
			result := parseCode(tc.code)
			s.Assert().Equal(tc.expected, result, "MUST correctly detect depend.RunSuite usage")
		})
	}
}

func (s *IntegrationSuite) TestBuildTagsPreservedInGeneratedFile() {
	// GOAL: Verify build tags are preserved from source file to generated file
	// Fixes GitHub issue #1: https://github.com/srgg/testify/issues/1
	//
	// TEST SCENARIO: Create test file with //go:build and // +build tags → run dependgen →
	// generated file preserves both build tags before the "Code generated" comment

	testCases := []struct {
		name        string
		fileContent string
	}{
		{
			name: "Build tags as first comment group",
			fileContent: `//go:build test
// +build test

package test

import (
	"testing"
	"github.com/srgg/testify/depend"
	"github.com/stretchr/testify/suite"
)

type MySuite struct {
	suite.Suite
}

func (s *MySuite) TestA() {}
func (s *MySuite) TestB() {}

func TestMySuite(t *testing.T) {
	depend.RunSuite(t, new(MySuite))
}`,
		},
		{
			name: "Build tags after copyright comment",
			fileContent: `// Copyright 2024 Example Corp
// All rights reserved

//go:build test
// +build test

package test

import (
	"testing"
	"github.com/srgg/testify/depend"
	"github.com/stretchr/testify/suite"
)

type MySuite struct {
	suite.Suite
}

func (s *MySuite) TestA() {}
func (s *MySuite) TestB() {}

func TestMySuite(t *testing.T) {
	depend.RunSuite(t, new(MySuite))
}`,
		},
	}

	for _, tc := range testCases {
		s.Run(tc.name, func() {
			testDir := s.TempDir().Build()

			testFile := filepath.Join(testDir, "suite_test.go")
			err := os.WriteFile(testFile, []byte(tc.fileContent), 0644)
			s.Require().NoError(err, "MUST write test file")

			// Run dependgen in auto-detect mode
			output, err := s.runDependgen(testDir, []string{"-v"}, map[string]string{"GOFILE": "suite_test.go"})
			s.Assert().NoError(err, "MUST generate successfully: %s", output)

			// Verify generated file contains both build tags
			generatedCode := s.assertGeneratedFile(testDir, "suite_depend_test.go",
				"//go:build test",
				"// +build test",
				"Code generated by dependgen",
				"MySuiteTestRegistry")

			// Verify build tags appear BEFORE the generated code comment (critical for Go toolchain)
			s.Assert().Regexp(`(?s)//go:build test\s+// \+build test\s+// Code generated by dependgen`, generatedCode,
				"MUST have build tags before generated code comment")

			// Copyright should NOT be copied to generated file
			if tc.name == "Build tags after copyright comment" {
				s.Assert().NotContains(generatedCode, "Copyright", "MUST NOT copy copyright to generated file")
			}
		})
	}
}

func TestDependgenSuite(t *testing.T) {
	suite.Run(t, new(IntegrationSuite))
}
